task:
        name: Build (Mono 5.14/Centos 7)
        container:
                image: jen20/cirrus-dotnet-linux:1.0
        env:
                GIT_CLONE_DEPTH: 1
                FrameworkPathOverride: /usr/lib/mono/4.6.2-api
        compile_script: 
                - dotnet msbuild /target:restore,compile src/cirrus-test.sln
        test_script:
                - dotnet test $(find ./src -maxdepth 1 -type d -name "*.Tests")

task:
        name: Build (Mono 5.14/Mac OS X High Sierra)
        osx_instance:
                image: high-sierra-xcode-9.4.1
        env:
                GIT_CLONE_DEPTH: 1
                FrameworkPathOverride: /usr/local/lib/mono/4.6.2-api
                PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/share/dotnet
        install_mono_script: 
                - brew install mono
                - brew cask install dotnet
        compile_script:
                - dotnet msbuild /target:restore,compile src/cirrus-test.sln
        test_script:
                - dotnet test $(find ./src -maxdepth 1 -type d -name "*.Tests")
