task:
        name: Build (Mono 5.14/Centos 7)
        container:
                image: jen20/cirrus-dotnet-linux:1.0
        env:
                GIT_CLONE_DEPTH: 1
                FrameworkPathOverride: /usr/lib/mono/4.6.2-api
        compile_script: 
                - dotnet msbuild /target:restore,compile src/cirrus-test.sln
        test_script:
                - dotnet test $(find ./src -maxdepth 1 -type d -name "*.Tests")

task:
        name: Build (.NET Framework 4.7.2/Windows)
        windows_container:
                image: microsoft/dotnet-framework:4.7.2-sdk
        env:
                GIT_CLONE_DEPTH: 1
        compile_script: 
                - dotnet msbuild /target:restore,compile src/cirrus-test.sln
        test_script:
                - echo FOR /F %%P IN ('dir /b /S *.Tests.csproj') DO dotnet test %%P > %%TEMP%%\run-tests-windows.cmd
                - "%%TEMP%%\run-tests-windows.cmd"

task:
        name: Build (Mono 5.14/Mac OS X High Sierra)
        osx_instance:
                image: high-sierra-xcode-9.4.1
        env:
                GIT_CLONE_DEPTH: 1
                FrameworkPathOverride: /usr/local/lib/mono/4.6.2-api
                PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/share/dotnet
        install_tools_script: 
                - brew cask install dotnet dotnet-sdk
                - brew install mono
        compile_script:
                - dotnet msbuild /target:restore,compile src/cirrus-test.sln
        test_script:
                - dotnet test $(find ./src -maxdepth 1 -type d -name "*.Tests")
