container:
        image: jen20/cirrus-dotnet-linux:1.0

task:
        name: Build (Mono 5.14/Centos 7)
        env:
                FrameworkPathOverride: /usr/lib/mono/4.6.2-api
        compile_script: dotnet msbuild /target:restore,compile src/cirrus-test.sln
        test_script: dotnet test $(find ./src -maxdepth 1 -type d -name "*.Tests")
