container:
        image: jen20/cirrus-dotnet-linux:1.0

task:
        name: Build (Mono 5.14/Centos 7)
        compile_script: dotnet msbuild src/cirrus-test.sln
        test_script: dotnet test $(find . -maxdepth 1 -type d -name "*.Tests")
